version: '3.7'
services:
    postgres:
        image: postgres:16
        restart: always
        environment:
          - POSTGRES_USER=counterblow_user
          - POSTGRES_PASSWORD=postgres123!?
          - POSTGRES_DB=counterblow_db
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql


# psql shortcut
# PGPASSWORD='postgres123!?' psql -h localhost -p 5438 -U counterblow_user -d counterblow_db