// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnDOMContentLoaded(arg1:string):Promise<void>;

export function SaveRule(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function StartBalancer(arg1:string,arg2:number):Promise<boolean>;

export function StopBalancer(arg1:string):Promise<string>;
