// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1:number,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;

export function OnDOMContentLoaded(arg1:string):Promise<void>;

export function RefreshRules():Promise<void>;

export function RemoveRule(arg1:number):Promise<void>;

export function StartBalancer(arg1:string,arg2:number):Promise<void>;

export function StopBalancer(arg1:string):Promise<string>;
