// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppLogAppend(arg1:string):Promise<string>;

export function StartBalancer(arg1:string):Promise<string>;

export function StopBalancer(arg1:string):Promise<string>;
