// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddRule'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function OnDOMContentLoaded(arg1) {
  return window['go']['main']['App']['OnDOMContentLoaded'](arg1);
}

export function RefreshRules() {
  return window['go']['main']['App']['RefreshRules']();
}

export function RemoveRule(arg1) {
  return window['go']['main']['App']['RemoveRule'](arg1);
}

export function StartBalancer(arg1, arg2) {
  return window['go']['main']['App']['StartBalancer'](arg1, arg2);
}

export function StopBalancer(arg1) {
  return window['go']['main']['App']['StopBalancer'](arg1);
}
