// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppLogAppend(arg1) {
  return window['go']['main']['App']['AppLogAppend'](arg1);
}

export function StartBalancer(arg1) {
  return window['go']['main']['App']['StartBalancer'](arg1);
}

export function StopBalancer(arg1) {
  return window['go']['main']['App']['StopBalancer'](arg1);
}
